[phases.setup]
nixPkgs = ["php", "phpExtensions.curl", "phpExtensions.mbstring", "phpExtensions.openssl", "phpExtensions.pdo", "phpExtensions.pdo_mysql", "phpExtensions.tokenizer"]

[phases.build]
commands = ["composer install --optimize-autoloader --no-dev"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
